Draft: Add USM support to OpenCL.jl
JuliaGPU/OpenCL.jl pull request #264
Opened 2024-10-25 19:28 UTC by VarLad

**Heavy WIP, incomplete for now. Expect very little to work.**

This exists so that I can, with time, ask for feedbacks and at a later point, for other people to be able to try this PR.

2025-01-13 07:52 UTC, VarLad commented
Tests still need to be ported, but any reviews in current functionality would be welcome!

2025-01-17 08:36 UTC, maleadt requested changes
Quick partial review. My biggest gripes are that this shouldn't have formatted the entire codebase, which makes reviewing very hard, and shouldn't have removed support for regular Buffers or SVM. Intel USM being an extension I don't think we should rely on it being available (SVM is questionable enough already, but at least is mandated by specific OpenCL versions).

2025-01-17 08:36 UTC, maleadt commented on lib/cl/CL.jl
> -include("svm.jl")
Why did you remove this functionality?

2025-01-17 08:36 UTC, maleadt commented on lib/cl/api.jl
> +    return ret
Unrelated formatting changes like that make it hard to review your PR. The formatter should only have run on changed code; did you format the entire codebase?

2025-01-17 08:36 UTC, maleadt commented on lib/cl/api.jl
> +            Only system drivers will be available. To enable JLL drivers, do not run Julia as an administrator."""
To prevent the formatter from spamming, keep your PR as draft for longer.

2025-01-17 08:36 UTC, maleadt commented on lib/cl/state.jl
> +=#
Remove this.

2025-01-17 08:36 UTC, maleadt commented on lib/cl/cmdqueue.jl
> +end
What's wrong with `cl.queue` from `state.jl`?

2025-01-17 08:36 UTC, maleadt commented on lib/cl/error.jl
> +    ),
Undo all the formatting changes here.

2025-01-17 08:36 UTC, maleadt commented on lib/cl/kernel.jl
>  end
This isn't SVM anymore.

2025-01-17 08:39 UTC, VarLad commented on lib/cl/api.jl
> +    return ret
I tried running Runic on the files it complained.

2025-01-17 08:40 UTC, VarLad commented on lib/cl/cmdqueue.jl
> +end
This is a testing artifact, we don't use or need this, will remove this.

2025-01-17 12:28 UTC, maleadt commented
```
julia> cl.svm_capabilities(cl.device())
(coarse_grain_buffer = true, fine_grain_buffer = false, fine_grain_system = false)

julia> cl.usm_capabilities(cl.device())
ERROR: CLError(code=-30, CL_INVALID_VALUE)
```

That should probably behave more nicely when USM isn't supported at all.

2025-01-17 12:42 UTC, maleadt requested changes

2025-01-17 12:42 UTC, maleadt commented
Something is wrong with CI (on master too); the CUDA tests are empty.

2025-01-20 12:57 UTC, maleadt commented
I've squashed the commits. Please use rebase in the future; merge commits only make things more annoying.

2025-01-20 12:59 UTC, maleadt commented on lib/cl/memory.jl
> +export device_alloc, host_alloc, shared_alloc, free #, properties, lookup_alloc
Feel free to mark conversations as resolved when you fixed something, that makes it easier to review.

2025-01-20 17:19 UTC, maleadt commented
The Memoization.jl dependency isn't great, also because it doesn't offer us thread safety (unless when using a ridiculously expensive datatype, like ThreadSafeDicts.jl). I wonder if we should copy the CUDA.jl LazyInitialized/`@memoize` implementation. Alternatively, for now we could just put the buffer type in the task local state, initialized when switching devices.

I'll have a closer look tomorrow.

2025-01-21 08:26 UTC, maleadt commented
I'm seeing lots of failures locally when testing non-PoCL platforms:

```
      From worker 2:	error in running finalizer: UndefRefError()
      From worker 2:	ext_clMemBlockingFreeINTEL at /home/tim/Julia/pkg/OpenCL/lib/cl/modified_fns.jl:34
      From worker 2:	#free#401 at /home/tim/Julia/pkg/OpenCL/lib/cl/memory/memory.jl:43 [inlined]
      From worker 2:	free at /home/tim/Julia/pkg/OpenCL/lib/cl/memory/memory.jl:28 [inlined]
      From worker 2:	release at /home/tim/Julia/pkg/OpenCL/src/pool.jl:78 [inlined]
      From worker 2:	#9 at /home/tim/Julia/pkg/OpenCL/src/array.jl:55
      From worker 2:	unknown function (ip: 0x71b84b70a752)
      From worker 2:	release at /home/tim/.julia/packages/GPUArrays/Mot2g/src/host/abstractarray.jl:42
      From worker 2:	unsafe_free! at /home/tim/.julia/packages/GPUArrays/Mot2g/src/host/abstractarray.jl:100 [inlined]
      From worker 2:	unsafe_free! at /home/tim/.julia/packages/GPUArrays/Mot2g/src/host/abstractarray.jl:115
      From worker 2:	unknown function (ip: 0x71b84b70a372)
      From worker 2:	run_finalizer at /cache/build/tester-amdci5-12/julialang/julia-release-1-dot-11/src/gc.c:299
```

I've squashed again and reverted all the unnecessary formatting changes. Will be taking another look later today / this week.

2025-01-21 08:49 UTC, VarLad commented
@maleadt Can you try running those tests individually? As in, `cd test; include("setup.jl"); include("kernel.jl")`
and see if you still encounter the same errors?
or alternatively, try removing `pocl_jll` from `using OpenCL, pocl_jll` in `tests/setup.jl`.
I have a feeling that the error is because of different processes are choosing context/devices differently/randomly...

2025-01-21 09:11 UTC, VarLad commented
I tried printing some logs and I see this:
![image](https://github.com/user-attachments/assets/659a43c6-2445-41d3-9c18-e1f3f8819ae4)

and I can't really make sense of this. Both are printing `cl.device()`
One in `test/setup.jl`, other in `test/array.jl`

Also, when I remove `pocl_jll` from testing, or test individually, it works out fine.

2025-01-21 09:20 UTC, VarLad commented
Ah, thanks for the tips. 
That is more convenient. I see that in runtests you cycle through different platforms and device...
I think thats where the error is coming from. 

For a solution I guess the functions defining CLArray need to be rerun everytime device changes?

2025-01-21 09:23 UTC, maleadt commented
The problem is probably that you're calling the wrong extension functions, since you simply look up `cl.platform()` in `ocl_extension`. The `free` function would probably have to switch to the correct platform as derived from the context in the buffer.

2025-01-23 09:45 UTC, VarLad commented on lib/cl/memory/svm.jl
Apologies for annoying you on this....
Regarding this change on line 35 (or 36)
```julia
function svm_free(buf::SharedVirtualMemory)
    clSVMFree(context(buf), buf)
    return
end
```
change.
Is that fine? As per https://registry.khronos.org/OpenCL/sdk/3.0/docs/man/html/clSVMFree.html
> Note that clSVMFree does not wait for previously enqueued commands that may be using svm_pointer to finish before freeing svm_pointer. It is the responsibility of the application to make sure that enqueued commands that use svm_pointer have finished before freeing svm_pointer. This can be done by enqueuing a blocking operation such as clFinish, clWaitForEvents, clEnqueueReadBuffer or by registering a callback with the events associated with enqueued commands and when the last enqueued command has finished freeing svm_pointer.

Shouldn't we try and keep the behavior close to the USM counterpart for the `free` function?

2025-01-23 09:52 UTC, VarLad commented on lib/cl/memory/svm.jl
Ah wait, never mind, you do the waiting part later down I guess.

2025-01-23 12:06 UTC, maleadt commented on lib/cl/memory/svm.jl
No actually that's a good comment; we need synchronize _before_ calling the free AFAIU.

2025-01-23 16:38 UTC, maleadt commented
Doesn't work on Intel, ironically:

```
❯ jl --project -e 'using OpenCL; cl.platform!("intel"); CLArray([1]) .+ 1'
Precompiling OpenCL...
  1 dependency successfully precompiled in 3 seconds. 64 already precompiled.
ERROR: CLError(code=-30, CL_INVALID_VALUE)
Stacktrace:
  [1] throw_api_error(res::Int32)
    @ OpenCL.cl ~/Julia/pkg/OpenCL/lib/cl/libopencl.jl:6
  [2] check
    @ ~/Julia/pkg/OpenCL/lib/cl/libopencl.jl:17 [inlined]
  [3] clSetKernelExecInfo
    @ ~/Julia/pkg/OpenCL/lib/cl/api.jl:34 [inlined]
```

2025-01-23 18:39 UTC, maleadt commented
No; turns out we weren't properly pushing to `svm_pointers` on master, so it didn't happen to call `clSetKernelExecInfo`.

2025-01-23 19:51 UTC, maleadt commented
This is the failing code path: https://github.com/intel/compute-runtime/blob/e48b52814958331d46bc6fb6398d6793fdc65049/opencl/source/api/api.cpp#L5300-L5302

Somehow the allocated pointer isn't recognized by the driver.

2025-01-24 04:02 UTC, VarLad commented
and this doesn't work for USM either?
Can we open a bug report on their side for this? It works with POCL and heck even with NVIDIA drivers...
Also, is your `platform` an Intel CPU or an Intel GPU? I think their CPU drivers might be problematic...
I'll try getting my hand on an Intel iGPU.

2025-01-24 09:36 UTC, maleadt commented
Alright, I think I finally got this in a place I'm happy with. It took a lot more work to get all the pieces (calling OpenCL extension functions, introduction of CLPtr, `Managed` and auto-synchronization, USM on PoCL as well as Intel, SVM and USM co-existence, etc) fully working and in a maintainable shape.

@VarLad Thanks for laying the groundwork here! For future work, I would suggest however to keep the scope of PRs minimal and create multiple ones. That will make it much easier to review as well as get everything working.

Feel free to give this a round of review before merging.

2025-01-24 14:31 UTC, VarLad commented
Does a version bump make sense for this PR? :slightly_smiling_face:

2025-01-24 19:26 UTC, maleadt commented
A release for sure, but in the pre-1.0 regime we can't do a minor release (which is considered breaking). So it'll be a patch bump.

2025-01-25 07:38 UTC, merged